### ISSUE TITLE
min php version / tag a release?

### ISSUE THREAD

**Issue by matt-allan** [dhotson/httpparser-php#2]
Hello,

I would like to add your extension to the [homebrew-php](https://github.com/Homebrew/homebrew-php) repo and I had 2 questions:

1.) What is the minimum version required?  I assume it is 5.4?

2.) Would you be willing to tag a release?

Thanks!

**Comment by dhotson** [comment]
Hi @matthew-james,

I think it should work on PHP5.4 .. I don't think it's been tested on 5.5+ sorry.

I'd be happy to help in whatever way I can. It's been quite a while since I last looked at this though. :)

**Comment by dhotson** [comment]
Also, I just added you as a collaborator on the repo, hopefully that gives you access to create tags etc.

**Comment by matt-allan** [comment]
Great, thanks!

**Comment by matt-allan** [comment]
Tested and works on 5.5 and 5.6

**Comment by dhotson** [comment]
Nice work. Thanks! :)
